fix: transaction preview fragment layout
tonwhales/wallet pull request #312
Opened 2022-11-17 09:29 UTC by vzhovnitsky

2022-11-17 09:47 UTC, dvlkv approved these changes

2022-11-17 09:48 UTC, dvlkv approved these changes

2022-12-07 15:21 UTC, dvlkv requested changes

2022-12-07 15:21 UTC, dvlkv commented on app/fragments/wallet/TransactionPreviewFragment.tsx
> +                            {'failed'}
Add i8n

2022-12-07 15:56 UTC, vzhovnitsky commented on app/fragments/wallet/TransactionPreviewFragment.tsx
> +                            {'failed'}
done

2022-12-07 19:58 UTC, dvlkv approved these changes
LGTM

2022-12-08 12:46 UTC, merged