feat: implementing ton-connect 2.0 including js - injected and remote bridges
tonwhales/wallet pull request #354
Opened 2023-02-23 12:23 UTC by vzhovnitsky

This needs a heavy review and probably a lot of refactoring.
https://user-images.githubusercontent.com/32094306/220904414-10bff28e-f6c4-4a63-a948-d0b7552e83cb.MP4

2023-03-07 12:04 UTC, dvlkv requested changes

2023-03-07 12:05 UTC, vzhovnitsky commented on app/engine/tonconnect/fetchManifest.ts
> +export async function fetchManifest(link: string) {
Indeed, will do!

2023-03-07 12:06 UTC, vzhovnitsky commented on app/fragments/apps/components/ConnectAppComponent.tsx
> +    useTrackEvent(MixpanelEvent.AppOpen, { url: props.endpoint, domain });
Yeah, you're right

2023-03-07 12:08 UTC, dvlkv commented on app/engine/tonconnect/TonConnect.ts
> +export class TonConnect {
TonConnectBridgeClient

2023-03-07 12:12 UTC, dvlkv requested changes

2023-03-07 12:12 UTC, dvlkv commented on app/fragments/secure/TonConnectAuthenticateFragment.tsx
> +            warn(error);
Rewrite to text error to prevent leaking keys

2023-03-07 15:02 UTC, vzhovnitsky commented on app/engine/tonconnect/fetchManifest.ts
> +export async function fetchManifest(link: string) {
Done

2023-03-07 15:13 UTC, vzhovnitsky commented on app/components/TransferBatch.tsx
> +        let walletKeys: WalletKeys;
Done

2023-03-07 15:13 UTC, vzhovnitsky commented on app/components/TransferSingle.tsx
> +        let transfer = await contract.createTransfer({
Done

2023-03-07 15:13 UTC, vzhovnitsky commented on app/engine/tonconnect/TonConnect.ts
> +export class TonConnect {
Done

2023-03-07 16:06 UTC, vzhovnitsky commented on app/engine/estimate/estimateFees.ts
>      const gasUsed = 3308;
Done

2023-03-08 15:27 UTC, dvlkv approved these changes
LGTM

2023-03-14 12:47 UTC, merged