v1.28.2
tonwhales/wallet pull request #445
Opened 2023-07-01 12:05 UTC by dvlkv

Fixed:
- TON DNS resolve bugs

2023-07-01 12:06 UTC, vzhovnitsky approved these changes

2023-07-01 13:01 UTC, whalestech approved these changes

2023-07-01 21:00 UTC, vzhovnitsky requested changes
Need to fix persistence codec and ledger transfer with new rootDnsAddress

2023-07-01 21:28 UTC, vzhovnitsky commented
I've fixed the issues in question with https://github.com/tonwhales/wallet/pull/446

2023-07-03 05:33 UTC, vzhovnitsky approved these changes
🚀

2023-07-03 14:34 UTC, whalestech approved these changes

2023-07-03 21:04 UTC, merged