Feat: whales liquid staking
tonwhales/wallet pull request #775
Opened 2024-02-15 13:26 UTC by vzhovnitsky

2024-03-29 14:43 UTC, dvlkv requested changes

2024-03-29 14:43 UTC, dvlkv commented on app/components/products/StakingProductComponent.tsx
> +    const liquidBalance = useMemo(() => {
create a hook: useLiquidStakingBalance

2024-03-29 14:43 UTC, dvlkv commented on app/engine/hooks/staking/useLiquidStakingMember.ts
> +            let contract = LiquidStakingPool.createFromAddress(pool);
whydnt just calculate address without fetching liquid staking contract?

2024-03-29 14:43 UTC, dvlkv commented on app/fragments/staking/LiquidStakingTransferFragment.tsx
> +function reduceAmountState(withdrawRate: bigint, depostRate: bigint, type: 'withdraw' | 'top_up') {
depositRate

2024-03-29 14:43 UTC, dvlkv commented on app/fragments/staking/LiquidStakingTransferFragment.tsx
> +        const wsTon = fromNano(toNano(computed.toFixed(9)));
Не рекомендую считать во float

2024-03-29 14:43 UTC, dvlkv commented on app/fragments/staking/LiquidStakingTransferFragment.tsx
> +        let value: bigint | null = null;
Это ни откуда не скопировано? может вынести в отдельный хук?

2024-04-01 11:31 UTC, vzhovnitsky commented on app/components/products/StakingProductComponent.tsx
> +    const liquidBalance = useMemo(() => {
✅

2024-04-01 11:31 UTC, vzhovnitsky commented on app/fragments/staking/LiquidStakingTransferFragment.tsx
> +        const wsTon = fromNano(toNano(computed.toFixed(9)));
✅

2024-04-01 11:31 UTC, vzhovnitsky commented on app/fragments/staking/LiquidStakingTransferFragment.tsx
> +function reduceAmountState(withdrawRate: bigint, depostRate: bigint, type: 'withdraw' | 'top_up') {
✅

2024-04-01 11:31 UTC, vzhovnitsky commented on app/fragments/staking/LiquidStakingTransferFragment.tsx
> +        let value: bigint | null = null;
✅

2024-04-01 11:32 UTC, vzhovnitsky commented on app/engine/hooks/staking/useLiquidStakingMember.ts
> +            let contract = LiquidStakingPool.createFromAddress(pool);
✅

2024-04-02 13:50 UTC, dvlkv approved these changes

2024-04-05 11:38 UTC, dvlkv approved these changes

2024-04-05 11:38 UTC, merged