feat: LP jettons support
tonwhales/wallet pull request #798
Opened 2024-03-27 12:02 UTC by vzhovnitsky

![photo_2024-03-27 14 01 51 (1)](https://github.com/tonwhales/wallet/assets/32094306/c6bd5da6-f79e-41ff-86cf-c987bb6d9469)
![photo_2024-03-27 14 01 51](https://github.com/tonwhales/wallet/assets/32094306/579bd545-281e-4baf-89ad-1d142ca9da31)
![photo_2024-03-27 14 01 50](https://github.com/tonwhales/wallet/assets/32094306/cd00e300-46d1-4c4f-9ca8-ecf20ea211f4)

2024-04-05 12:26 UTC, dvlkv requested changes

2024-04-05 12:26 UTC, dvlkv commented on app/components/products/JettonProductItem.tsx
> +    let symbol = props.jetton.symbol ? ` ${props.jetton.symbol}` : '';
props.jetton.symbol ?? ''?

2024-04-05 12:32 UTC, vzhovnitsky commented on app/fragments/dev/DeveloperToolsFragment.tsx
> +        queryClient.invalidateQueries();
sure

2024-04-05 12:39 UTC, vzhovnitsky commented on app/components/products/JettonProductItem.tsx
> +    let symbol = props.jetton.symbol ? ` ${props.jetton.symbol}` : '';
✅

2024-04-24 14:22 UTC, dvlkv approved these changes

2024-04-30 14:33 UTC, dvlkv approved these changes

2024-04-30 14:33 UTC, merged