Feat: browser fragment with listings and search
tonwhales/wallet pull request #881
Opened 2024-05-10 09:42 UTC by vzhovnitsky

2024-05-20 14:31 UTC, dvlkv commented on app/components/ATextInput.tsx
> +    inpoutMode?: InputModeOptions,
inputMode

2024-05-20 14:45 UTC, vzhovnitsky commented on app/components/ATextInput.tsx
> +    inpoutMode?: InputModeOptions,
fixed

2024-05-20 15:16 UTC, dvlkv requested changes

2024-05-20 15:16 UTC, dvlkv commented on app/engine/api/fetchBrowserSuggestionsGoogle.ts
> +    return [];
А если упал поиск то может быть просто вести на Гугл ссылку?

2024-05-20 15:16 UTC, dvlkv commented on app/components/browser/BrowserSearch.tsx
> +        const reachable = await checkUrlReachability(url);
Тут навигация завязана на асинхронную функцию, а она лочит поиск? Сейчас читаю и кажется что оно просто повиснет и даст еще пару раз на кнопку нажать.

2024-05-20 17:51 UTC, vzhovnitsky commented on app/components/browser/BrowserSearch.tsx
> +        const reachable = await checkUrlReachability(url);
done

2024-05-20 17:51 UTC, vzhovnitsky commented on app/engine/api/fetchBrowserSuggestionsGoogle.ts
> +    return [];
добавил

2024-05-20 21:27 UTC, vzhovnitsky commented on app/fragments/utils/DAppWebViewFragment.tsx
> +            const iShare = options.findIndex((i) => i === t('browser.share'));
done

2024-05-21 08:09 UTC, dvlkv approved these changes

2024-05-21 08:09 UTC, merged